/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewdleIndexRouteImport } from './routes/reviewdle/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ReviewdleGameIdRouteImport } from './routes/reviewdle/$gameId'
import { Route as ReviewdleAdminIndexRouteImport } from './routes/reviewdle/admin/index'
import { Route as ReviewdleAdminAddRouteImport } from './routes/reviewdle/admin/add'
import { Route as ReviewdleAdminEditGameIdRouteImport } from './routes/reviewdle/admin/edit/$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewdleIndexRoute = ReviewdleIndexRouteImport.update({
  id: '/reviewdle/',
  path: '/reviewdle/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewdleGameIdRoute = ReviewdleGameIdRouteImport.update({
  id: '/reviewdle/$gameId',
  path: '/reviewdle/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewdleAdminIndexRoute = ReviewdleAdminIndexRouteImport.update({
  id: '/reviewdle/admin/',
  path: '/reviewdle/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewdleAdminAddRoute = ReviewdleAdminAddRouteImport.update({
  id: '/reviewdle/admin/add',
  path: '/reviewdle/admin/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewdleAdminEditGameIdRoute =
  ReviewdleAdminEditGameIdRouteImport.update({
    id: '/reviewdle/admin/edit/$gameId',
    path: '/reviewdle/admin/edit/$gameId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reviewdle/$gameId': typeof ReviewdleGameIdRoute
  '/login': typeof LoginIndexRoute
  '/reviewdle': typeof ReviewdleIndexRoute
  '/reviewdle/admin/add': typeof ReviewdleAdminAddRoute
  '/reviewdle/admin': typeof ReviewdleAdminIndexRoute
  '/reviewdle/admin/edit/$gameId': typeof ReviewdleAdminEditGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reviewdle/$gameId': typeof ReviewdleGameIdRoute
  '/login': typeof LoginIndexRoute
  '/reviewdle': typeof ReviewdleIndexRoute
  '/reviewdle/admin/add': typeof ReviewdleAdminAddRoute
  '/reviewdle/admin': typeof ReviewdleAdminIndexRoute
  '/reviewdle/admin/edit/$gameId': typeof ReviewdleAdminEditGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reviewdle/$gameId': typeof ReviewdleGameIdRoute
  '/login/': typeof LoginIndexRoute
  '/reviewdle/': typeof ReviewdleIndexRoute
  '/reviewdle/admin/add': typeof ReviewdleAdminAddRoute
  '/reviewdle/admin/': typeof ReviewdleAdminIndexRoute
  '/reviewdle/admin/edit/$gameId': typeof ReviewdleAdminEditGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reviewdle/$gameId'
    | '/login'
    | '/reviewdle'
    | '/reviewdle/admin/add'
    | '/reviewdle/admin'
    | '/reviewdle/admin/edit/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reviewdle/$gameId'
    | '/login'
    | '/reviewdle'
    | '/reviewdle/admin/add'
    | '/reviewdle/admin'
    | '/reviewdle/admin/edit/$gameId'
  id:
    | '__root__'
    | '/'
    | '/reviewdle/$gameId'
    | '/login/'
    | '/reviewdle/'
    | '/reviewdle/admin/add'
    | '/reviewdle/admin/'
    | '/reviewdle/admin/edit/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewdleGameIdRoute: typeof ReviewdleGameIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ReviewdleIndexRoute: typeof ReviewdleIndexRoute
  ReviewdleAdminAddRoute: typeof ReviewdleAdminAddRoute
  ReviewdleAdminIndexRoute: typeof ReviewdleAdminIndexRoute
  ReviewdleAdminEditGameIdRoute: typeof ReviewdleAdminEditGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewdle/': {
      id: '/reviewdle/'
      path: '/reviewdle'
      fullPath: '/reviewdle'
      preLoaderRoute: typeof ReviewdleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewdle/$gameId': {
      id: '/reviewdle/$gameId'
      path: '/reviewdle/$gameId'
      fullPath: '/reviewdle/$gameId'
      preLoaderRoute: typeof ReviewdleGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewdle/admin/': {
      id: '/reviewdle/admin/'
      path: '/reviewdle/admin'
      fullPath: '/reviewdle/admin'
      preLoaderRoute: typeof ReviewdleAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewdle/admin/add': {
      id: '/reviewdle/admin/add'
      path: '/reviewdle/admin/add'
      fullPath: '/reviewdle/admin/add'
      preLoaderRoute: typeof ReviewdleAdminAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewdle/admin/edit/$gameId': {
      id: '/reviewdle/admin/edit/$gameId'
      path: '/reviewdle/admin/edit/$gameId'
      fullPath: '/reviewdle/admin/edit/$gameId'
      preLoaderRoute: typeof ReviewdleAdminEditGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewdleGameIdRoute: ReviewdleGameIdRoute,
  LoginIndexRoute: LoginIndexRoute,
  ReviewdleIndexRoute: ReviewdleIndexRoute,
  ReviewdleAdminAddRoute: ReviewdleAdminAddRoute,
  ReviewdleAdminIndexRoute: ReviewdleAdminIndexRoute,
  ReviewdleAdminEditGameIdRoute: ReviewdleAdminEditGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
